// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    'HeroiconsSolid:film': typeof import('~icons/heroicons-solid/film')['default']
    'HeroiconsSolid:hashtag': typeof import('~icons/heroicons-solid/hashtag')['default']
    'HeroiconsSolid:home': typeof import('~icons/heroicons-solid/home')['default']
    'HeroiconsSolid:mail': typeof import('~icons/heroicons-solid/mail')['default']
    NavigationRail: typeof import('./components/NavigationRail.vue')['default']
    NavigationRailItem: typeof import('./components/NavigationRailItem.vue')['default']
    README: typeof import('./components/README.md')['default']
  }
}

export { }
