// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Background: typeof import('./components/global/Background.vue')['default']
    ContactForwarding: typeof import('./components/ContactForwarding.vue')['default']
    Footer: typeof import('./components/global/Footer.vue')['default']
    Header: typeof import('./components/global/Header.vue')['default']
    'HeroiconsSolid:search': typeof import('~icons/heroicons-solid/search')['default']
    'HeroiconsSolid:sortAscending': typeof import('~icons/heroicons-solid/sort-ascending')['default']
    'HeroiconsSolid:sortDescending': typeof import('~icons/heroicons-solid/sort-descending')['default']
    IconBadge: typeof import('./components/global/IconBadge.vue')['default']
    IconLinkExternal: typeof import('./components/global/IconLinkExternal.vue')['default']
    IconLinkInternal: typeof import('./components/global/IconLinkInternal.vue')['default']
    LoginForm: typeof import('./components/forms/LoginForm.vue')['default']
    Logo: typeof import('./components/global/Logo.vue')['default']
    MehmComments: typeof import('./components/mehms/MehmComments.vue')['default']
    MehmForm: typeof import('./components/forms/MehmForm.vue')['default']
    MehmPost: typeof import('./components/mehms/MehmPost.vue')['default']
    MehmsGallery: typeof import('./components/mehms/MehmsGallery.vue')['default']
    MehmsToolbar: typeof import('./components/mehms/MehmsToolbar.vue')['default']
    NavigationBar: typeof import('./components/global/NavigationBar.vue')['default']
    README: typeof import('./components/README.md')['default']
    RegisterForm: typeof import('./components/forms/RegisterForm.vue')['default']
    RickFoundYou: typeof import('./components/RickFoundYou.vue')['default']
    UserForm: typeof import('./components/forms/UserForm.vue')['default']
  }
}

export { }
