// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./components/global/footer/Footer.vue')['default']
    FooterLinkExternal: typeof import('./components/global/footer/FooterLinkExternal.vue')['default']
    FooterLinkInternal: typeof import('./components/global/footer/FooterLinkInternal.vue')['default']
    Grid: typeof import('./components/global/background/Grid.vue')['default']
    Header: typeof import('./components/global/header/Header.vue')['default']
    Hero: typeof import('./components/global/background/Hero.vue')['default']
    'HeroiconsSolid:search': typeof import('~icons/heroicons-solid/search')['default']
    'HeroiconsSolid:sortAscending': typeof import('~icons/heroicons-solid/sort-ascending')['default']
    'HeroiconsSolid:sortDescending': typeof import('~icons/heroicons-solid/sort-descending')['default']
    IconBadge: typeof import('./components/IconBadge.vue')['default']
    Logo: typeof import('./components/global/header/Logo.vue')['default']
    MehmsGallery: typeof import('./components/mehms/MehmsGallery.vue')['default']
    MehmsJson: typeof import('./components/mehms/MehmsJson.vue')['default']
    MehmToolbar: typeof import('./components/mehms/MehmToolbar.vue')['default']
    NavigationRail: typeof import('./components/NavigationRail.vue')['default']
    PageMehmObject: typeof import('./components/archive/PageMehmObject.vue')['default']
    README: typeof import('./components/README.md')['default']
  }
}

export { }
